# Generated by Django 4.2.16 on 2024-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category_comment_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
